try {
    console.log('Normal');
} catch {
    console.log('error');
}